### ISSUE TITLE
Museum API Arazzo Example Issues

### ISSUE THREAD

**Issue by TristanSpeakEasy** [Redocly/museum-openapi-example#37]
Hi, 

I was just going over the example Arazzo documents you have here:

- https://github.com/Redocly/museum-openapi-example/blob/main/arazzo/museum-api.arazzo.yaml
- https://github.com/Redocly/museum-openapi-example/blob/main/arazzo/museum-tickets.arazzo.yaml

And think there are a few issues in them:

I found similar issues in both documents:

```
[73:27] body reference must be empty or start with #: $response.body.eventId
[74:17] body reference must be empty or start with #: $response.body.name
[109:27] body reference must be empty or start with #: $response.body.eventId
```

From my reading of the Arazzo specification I believe body runtime expressions like this should be `$response.body#/eventId` ie the runtime expression to the body and then a json pointer to the field within.

This is based on the ABNF syntax here: https://spec.openapis.org/arazzo/latest.html#runtime-expressions

which defined the `expression` as `"$response." source`, `source` as `source = ( header-reference / query-reference / path-reference / body-reference )` and `body-reference` as `body-reference = "body" ["#" json-pointer ]`

**Comment by adamaltman** [comment]
Yes, these are clearly wrong. I didn't see your comment here. Someone else raised this issue today and I'll open a fix here in a few minutes... the challenges of maintaining a completely fake API 😆
